@extends('layouts.general')
@section('content')
  @component('components.header')
  @endcomponent
  <section class="about">
    <h2>About</h2>
    <p>Disclaimer, text generated by <a href="https://talktotransformer.com/">https://talktotransformer.com/</a></p>
    <div class="information">
      <p>Employees is a revolutionary business management software, which makes it easy for managers to manage the business while still remaining free to work and improve their skills. It combines executive accountability with the power to manage within your office, including WPA2 secure WiFi. It's flexible enough to meet your needs for your business but will help you keep your jobs. Features include: Multi-language support
        <br><br>
        "Paperless" billing
        <br><br>
        Share via email
        <br><br>
        Redundant cloud storage
        <br><br>
        Unlimited # of users
        <br><br>
        Client IT support
        <br><br>
        Money back guarantee
        <br><br>
        Full setup for $
      </p>
      <img src="https://images.pexels.com/photos/3182925/pexels-photo-3182925.jpeg?cs=srgb&dl=white-mountain-and-white-clouds-3182925.jpg&fm=jpg" alt="">
    </div>
  </section>
@endsection
