@extends('layouts.general')
@section('content')
  @component('components.header')
  @endcomponent
  <section class="about">
    <h2>About</h2>
    <div class="information">
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Error, odio est! Perspiciatis, repellat tenetur odit perferendis libero itaque architecto ad harum eum, sit eos illum dignissimos hic ipsa earum nemo tempore laudantium quo magnam consequuntur, dolorem porro ab. Nostrum illum architecto quod provident fuga nihil odio ad minima. Sint quasi nam non laborum dolorum dolorem eveniet autem assumenda totam, qui ut, beatae quo inventore voluptates expedita nesciunt eum voluptate fugit ipsum temporibus, blanditiis id. Atque ab accusantium optio, tenetur tempora ipsum animi modi nemo possimus numquam pariatur repudiandae minus temporibus consequuntur molestiae aperiam quod minima! Similique alias placeat magnam, velit iure veritatis! Autem maiores quis aperiam libero. Ea earum deleniti voluptate praesentium tenetur fugit minus ad, vel possimus odit distinctio laudantium? Vitae, nam nihil unde, ut error aperiam voluptatibus ducimus dolor, eligendi asperiores consectetur hic iste porro magni dolorem ab doloribus sapiente inventore eos! Dolor, ipsam soluta earum voluptate dolorum atque assumenda consequatur sequi asperiores quae. Assumenda nam sequi esse perspiciatis expedita totam ipsum praesentium! Cumque, laboriosam, debitis iste earum illum autem officiis esse error fugiat alias consequuntur sed beatae adipisci minus dolorem laborum? Doloribus quibusdam accusantium numquam rem quisquam pariatur laborum quo nostrum eos, ut ipsam nam, veritatis fugiat, quam debitis facilis. Obcaecati optio itaque reiciendis deserunt reprehenderit voluptates iusto provident. Ab inventore laborum non ex perspiciatis aspernatur laudantium. Dicta vero quae tempore dolor recusandae architecto perspiciatis vel neque nemo esse fuga voluptatum repellendus minima autem itaque facilis, magni consequatur, at tenetur dignissimos earum incidunt numquam accusantium. Natus adipisci tempore repellendus mollitia dolorum delectus maiores, excepturi aliquam atque sit, ipsum, aliquid eaque eveniet beatae perferendis illo corrupti harum. Unde deleniti, quo veritatis numquam consequuntur nobis nulla? Provident, vitae quae! Aut hic eius dolor! Aut quia ipsum repudiandae totam, laboriosam aliquam. Commodi esse repudiandae alias aliquam tempora pariatur ad ex?</p>
      <img src="https://images.pexels.com/photos/3182925/pexels-photo-3182925.jpeg?cs=srgb&dl=white-mountain-and-white-clouds-3182925.jpg&fm=jpg" alt="">
    </div>
  </section>
@endsection
